### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by albenstein** [JamFox/zabbix-slurm-template#2]
We are using slurm controller on headnode server and compute nodes has slurm client. On headnode server we've installed zabbix agent. On this scenerio, zabbix slurm templates get hostname of headnode server which is not in slurm queue. Could you please change this for getting slurm state of compute nodes?

**Comment by JamFox** [comment]
This is not the intended use of this template as it does not do automatic discovery. This was my initial plan actually to discover all nodes from the headnode, but other work got in the way and I left it simple: the template is applied to each node individually.

I have corrected the README in [be4e5026956e1ff96463d694135ab7ccc3dd5df5](https://github.com/JamFox/zabbix-slurm-template/commit/be4e5026956e1ff96463d694135ab7ccc3dd5df5).
